---
:at_tags: false
:autolink: true
:color: true
:inline_footnotes: false
:intra_emphasis: true
:lax_spacing: true
:links: :inline
:local_images: true
:mmd_metadata: true
:pager: true
:preserve_linebreaks: true
:remote_images: true
:syntax_highlight: true
:taskpaper: false
:theme: default
:transclude: true
:width: 0
:wiki_links: false
